# Generated by Django 5.1 on 2024-08-25 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo_cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registeredphotocard",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 25, 8, 48, 10, 201544, tzinfo=datetime.timezone.utc
                ),
                verbose_name="판매 기한 날짜",
            ),
            preserve_default=False,
        ),
    ]
